run:
  timeout: 3m

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive

issues:
  exclude-dirs:
    - bin
    - tmp
